name: CI

on:
  push:
    branches:
      - '**'
  repository_dispatch:
    types:
      check_connector_for_breaking_changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action/@nightly
        with:
          args: build ./twilio
      - name: Ballerina Test
        uses: ballerina-platform/ballerina-action/@nightly
        with:
            args:
                test --test-report --code-coverage --coverage-format=xml ./twilio
        env:
            ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
            AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
            SAMPLE_FROM_MOBILE: ${{ secrets.SAMPLE_FROM_MOBILE }}
            SAMPLE_TO_MOBILE: ${{ secrets.SAMPLE_TO_MOBILE }}
            SAMPLE_MESSAGE: ${{ secrets.SAMPLE_MESSAGE }}
            SAMPLE_WHATSAPP_SANDBOX: ${{ secrets.SAMPLE_WHATSAPP_SANDBOX }}
            SAMPLE_TWIML_URL: ${{ secrets.SAMPLE_TWIML_URL }}
            twilioAPIKey: ${{ secrets.twilioAPIKey }}
            twilioAPISecret: ${{ secrets.twilioAPISecret }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      - name: Alert notifier on failure
        if: failure() && (github.event.action == 'check_connector_for_breaking_changes')
        run: |
          curl -X POST \
          'https://api.github.com/repos/ballerina-platform/ballerina-release/dispatches' \
          --header 'Accept: application/vnd.github.v3+json' \
          --header 'Authorization: Bearer ${{ secrets.BALLERINA_BOT_TOKEN }}' \
          --data-raw '{
            "event_type": "notify-ballerinax-connector-build-failure",
            "client_payload": {
              "repoName": "module-ballerinax-twilio",
              "workflow": "CI"
            }
          }'
