name: Daily build without tests

on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Build Ballerina package
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action/@nightly
        with:
          args: build ./twilio
      - name: Ballerina Test
        uses: ballerina-platform/ballerina-action/@nightly
        with:
            args:
                test --test-report --code-coverage --coverage-format=xml ./twilio
        env:
            ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
            AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
            SAMPLE_FROM_MOBILE: ${{ secrets.SAMPLE_FROM_MOBILE }}
            SAMPLE_TO_MOBILE: ${{ secrets.SAMPLE_TO_MOBILE }}
            SAMPLE_MESSAGE: ${{ secrets.SAMPLE_MESSAGE }}
            SAMPLE_WHATSAPP_SANDBOX: ${{ secrets.SAMPLE_WHATSAPP_SANDBOX }}
            SAMPLE_TWIML_URL: ${{ secrets.SAMPLE_TWIML_URL }}
            twilioAPIKey: ${{ secrets.twilioAPIKey }}
            twilioAPISecret: ${{ secrets.twilioAPISecret }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      # Send notification when build fails
      - name: Notify failure
        if: ${{ failure() }}
        run: |
          curl -X POST \
          'https://api.github.com/repos/ballerina-platform/ballerina-release/dispatches' \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'Authorization: Bearer ${{ secrets.BALLERINA_BOT_TOKEN }}' \
          --data "{
            \"event_type\": \"notify-build-failure\",
            \"client_payload\": {
              \"repoName\": \"module-ballerinax-twilio\"
            }
          }"
