name: Pull Build

on: [ pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action/@nightly
        with:
          args: build ./twilio
      - name: Ballerina Tests
        # tests will be skipped if the PR is from a forked repository (as the secrets are not available)
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        uses: ballerina-platform/ballerina-action/@nightly
        with:
          args: bal test --test-report --code-coverage --coverage-format=xml ./twilio
        env:
          ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          SAMPLE_FROM_MOBILE: ${{ secrets.SAMPLE_FROM_MOBILE }}
          SAMPLE_TO_MOBILE: ${{ secrets.SAMPLE_TO_MOBILE }}
          SAMPLE_MESSAGE: ${{ secrets.SAMPLE_MESSAGE }}
          SAMPLE_WHATSAPP_SANDBOX: ${{ secrets.SAMPLE_WHATSAPP_SANDBOX }}
          SAMPLE_TWIML_URL: ${{ secrets.SAMPLE_TWIML_URL }}
          twilioAPIKey: ${{ secrets.twilioAPIKey }}
          twilioAPISecret: ${{ secrets.twilioAPISecret }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
